### ISSUE TITLE
What's the license for this?

### ISSUE THREAD

**Issue by mohlsen** [marten-de-vries/killable#2]
No mention of a Open Source License for this in the readme or license file.  Although I see one on npm for ISC?

**Comment by marten-de-vries** [comment]
My take on this is that if it's copyrightable in the first place, I want everyone to be able to use it, without restrictions. I chose ISC in the npm file in the hope to satisfy that. If you need an actual LICENSE file/copyright header, or the license doesn't suit you for some reason, just say so and I will try to accomodate you.

**Comment by char0n** [comment]
According the ISC license text, the code distribution must be accompanied by full license text and copyright notice. NPM distribution is a form of code distribution too. @marten-de-vries can you pls include a `LICENSE` file inside your repo containing full license text https://opensource.org/licenses/ISC and properly filled copyright notice ? Also patch release of this library will be needed to include the `LICENSE` file in npm package. 

At this moment your library has proprietary code in npm package and inside this repository and nobody can nor should use it.

**Comment by marten-de-vries** [comment]
@char0n Done.

**Comment by char0n** [comment]
Very cool, thank you.
